import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import StoreProvider from '@/app/redux/StoreProvider';
import { ThemeOptions, ThemeProvider } from '@mui/material/styles';
import theme from './theme';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <StoreProvider>
          <body className={`${inter.className} flex flex-col min-h-screen`}>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
          </body>
        </StoreProvider>
      </ThemeProvider>
    </html>
  );
}
